name: Hello World Workflow

# Trigger the workflow on push to the main branch or on any pull request.
on:
  push:
    branches:
      - main

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (required in most workflows)
      - name: Checkout code
        uses: actions/checkout@v3

      # Run a simple Hello World script
      - name: Say Hello World
        run: echo "Hello, World!"
